language: node_js

node_js:
  - "node"
  - "8"

deploy:
  provider: npm
  email: danielpa9708@gmail.com
  api_key:
    secure: gHD0tgVqYn+3E7zIwWP0stJXSTbBZm9kzTzo0DT7HV9aDvVhd3qDqQQLbbRtkfkHZYSjBqw/dTsj6eoqGtPBO6U8aK62nFRqdiCk9hMkLIyRjHMX652D0Ow6ZQTMaOMw5Le0u0DQ2PFhKw6MFVi/K05Ww+Vfg9XsTK0TjQVJD11y+HpjLGaV1x803NlX+rYBEO40Sq5h5WIIS7ypWU6WP64oaszeAhnbUlhsEPg85x6u33sypNqfVLpaKgnY6qZZEqj96bj8KG/93C2PiPMQos7PuscKySfr7aGYCqgxXofo7xOUjgxau/q00hd0XGIpGcK5kr2LljMJYFquvwcT5oAYahZJRK/uOPBOw1ADs+trUJeIf1EeJcWCVCwivAjYk0AxoICZXy5dZnBD7wG0EMrPXmwhbW+epnd/5jP4ly/aTg0eiG9mvI5PQV/qtzYqjJdTcG1dwG2rES/q7kTDPm5NZ8l26aFhRn3ou3IKFtGqA2EVg8pPa23dJXiWBwiTjcn/CKllBnAxBlx/uDmd2uS7t0pMfKFicOIhhHYaBLpTOYWlYFsyuKf73UeiOFpDvTmgGyWNbu2cJlspTAKWs0lwdnW12Jqda5cviBluxs4ikRNXrEisBPwEoWPFziCC8Vh0cLoTFPcYxsbTw+Rx2E/JfEcb4um4tzxA80pyPEI=
  on:
    branch: master
